name: Build Commit

on:
  workflow_call:
    inputs:
      build-type:
        required: true
        type: string
      malloc-impl:
        required: true
        type: string
      prerelease:
        required: true
        type: string

jobs:
  SislDeps:
    uses: eBay/sisl/.github/workflows/build_dependencies.yml@master
    with:
      branch: master
      build-type: ${{ inputs.build-type }}
      malloc-impl: ${{ inputs.malloc-impl }}
      prerelease: ${{ inputs.prerelease }}
  IOMgrDeps:
    needs: SislDeps
    uses: ./.github/workflows/build_dependencies.yml
    with:
      branch: master
      build-type: ${{ inputs.build-type }}
      malloc-impl: ${{ inputs.malloc-impl }}
      prerelease: ${{ inputs.prerelease }}
  BuildCommit:
    steps:
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: Setup Conan
      run: |
        sudo apt-get install -y python3-pyelftools libaio-dev
        python -m pip install --upgrade pip
        python -m pip install pyelftools
        python -m pip install conan~=1.0
        conan user
        conan profile new --detect default
        # Set std::string to non-CoW C++11 version
        sed -i 's,compiler.libcxx=libstdc++$,compiler.libcxx=libstdc++11,g' ~/.conan/profiles/default

    - name: Restore Sisl 3rdParty Cache
      id: restore-cache-sisl
      uses: actions/cache/restore@v3
      with:
        path: |
          ~/.conan/data
        key: SislDeps-${{ matrix.build-type }}-${{ matrix.malloc-impl }}-${{ matrix.prerelease }}

    - name: Restore IOMgr 3rdParty Cache
      id: restore-3rd-party
      uses: actions/cache/restore@v3
      with:
        path: |
          ~/.conan/data
        key: IOMgrDeps-${{ matrix.build-type }}-${{ matrix.malloc-impl }}-${{ matrix.prerelease }}

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build
      run: |
        conan create \
            -o sisl:prerelease=${{ matrix.prerelease }} \
            -o sisl:malloc_impl=${{ matrix.malloc-impl }} \
            -o iomgr:testing=off \
            -s build_type=${{ matrix.build-type }} \
            --build missing \
            . \
            oss/master
