name: IOManager Merge Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - stable/v8.x

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        platform: ["ubuntu-22.04"]
        build-type: ["Debug", "Release"]
        malloc-impl: ["libc", "tcmalloc", "jemalloc"]
        prerelease: ["True", "False"]
        exclude:
          - malloc-impl: jemalloc
            build-type: Debug
          - malloc-impl: tcmalloc
            build-type: Debug
          - malloc-impl: tcmalloc
            prerelease: "True"
          - malloc-impl: jemalloc
            prerelease: "False"
          - malloc-impl: libc
            build-type: Release

    uses: ./.github/workflows/build_commit.yml
    with:
      platform: ${{ matrix.platform }}
      build-type: ${{ matrix.build-type }}
      malloc-impl: ${{ matrix.malloc-impl }}
      prerelease: ${{ matrix.prerelease }}
  ChainBuild:
    runs-on: "ubuntu-22.04"
    steps:
    - name: Start Homestore Build
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.CHAIN_BUILD_TOKEN }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/eBay/homestore/actions/workflows/merge_conan_build.yml/dispatches \
          -d '{"ref":"master","inputs":{}}'
      if: ${{ github.ref == 'refs/heads/master' }}
