name: IOManager PR Build

on:
  pull_request:
    branches:
      - master

jobs:
  BuildSISL:
    strategy:
      fail-fast: true
      matrix:
        build-type: ["Debug", "Release"]
        malloc-impl: ["libc", "tcmalloc", "jemalloc"]
        prerelease: ["False"]
        exclude:
          - build-type: Debug
            malloc-impl: tcmalloc
          - build-type: Debug
            malloc-impl: jemalloc
          - build-type: Release
            malloc-impl: libc
    uses: ./.github/workflows/build_sisl.yml
    with:
      build-type: ${{ matrix.build-type }}
      malloc-impl: ${{ matrix.malloc-impl }}
      prerelease: "False"

  CacheDependencies:
    needs: BuildSISL
    strategy:
      fail-fast: true
      matrix:
        build-type: ["Debug", "Release"]
        malloc-impl: ["libc", "tcmalloc", "jemalloc"]
        prerelease: ["False"]
        exclude:
          - build-type: Debug
            malloc-impl: tcmalloc
          - build-type: Debug
            malloc-impl: jemalloc
          - build-type: Release
            malloc-impl: libc
    uses: ./.github/workflows/build_dependencies.yml
    with:
      branch: master
      build-type: ${{ matrix.build-type }}
      malloc-impl: ${{ matrix.malloc-impl }}
      prerelease: ${{ matrix.prerelease }}

  BuildPR:
    needs: CacheDependencies
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        # Currently folly in conan-center has a bug when used with gcc 11.3 and sanitizer
        # sanitize: ["True", "False"]
        build-type: ["Debug", "Release"]
        malloc-impl: ["libc", "tcmalloc", "jemalloc"]
        prerelease: ["False"]
        exclude:
          - build-type: Debug
            malloc-impl: tcmalloc
          - build-type: Debug
            malloc-impl: jemalloc
          - build-type: Release
            malloc-impl: libc
          # - build-type: Release
          # sanitize: "True"

    steps:
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: Setup Conan
      run: |
        sudo apt-get install -y python3-pyelftools libaio-dev
        python -m pip install --upgrade pip
        python -m pip install pyelftools
        python -m pip install conan~=1.0
        conan user
        conan profile new --detect default
        # Set std::string to non-CoW C++11 version
        sed -i 's,compiler.libcxx=libstdc++$,compiler.libcxx=libstdc++11,g' ~/.conan/profiles/default

    - name: Restore Sisl 3rdParty Cache
      id: restore-cache-sisl
      uses: actions/cache/restore@v3
      with:
        path: |
          ~/.conan/data
        key: SislDeps-${{ matrix.build-type }}-${{ matrix.malloc-impl }}-${{ matrix.prerelease }}

    - name: Restore IOMgr 3rdParty Cache
      id: restore-3rd-party
      uses: actions/cache/restore@v3
      with:
        path: |
          ~/.conan/data
        key: IOMgrDeps-${{ matrix.build-type }}-${{ matrix.malloc-impl }}-${{ matrix.prerelease }}

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build
      run: |
        conan create \
            -o sisl:prerelease=${{ matrix.prerelease }} \
            -o sisl:malloc_impl=${{ matrix.malloc-impl }} \
            -o iomgr:testing=off \
            -s build_type=${{ matrix.build-type }} \
            --build missing \
            . \
            oss/master
